# Generated by Django 3.1.7 on 2021-03-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vanity_app', '0003_service_booked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='booked_users',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date',
        ),
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vanity_app.user')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vanity_app.service')),
            ],
        ),
    ]
