# Generated by Django 3.1.7 on 2021-03-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vanity_app', '0004_auto_20210323_0141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apointment',
            new_name='Appointment',
        ),
    ]
